### PR TITLE
Support for Error-prone

### PR DESCRIPTION
**Pull request by PragatiSukhija**

### CODE REVIEW

**Comment by bowbahdoe** [comment]
I'm not rejecting this out of hand, but I'm not super jazzed about running that every time. Maybe an option in the UI? The main reason I would consider it is for folks to try out null analysis w/ jspecify but its unclear if thats the best way to do it.

**Comment by PragatiSukhija** [comment]
Apologies, Ethan. This PR was not intended. I was experimenting with an error-prone integration and hosting it on Railway, which automatically raised the PR after a successful deployment. The integration isn't fully tested, nor do I plan to keep it integrated with the build. I definitely prefer it as a separate option. I'm glad the PR was denied. Thanks for your input.

**Comment by PragatiSukhija** [comment]
Closing the PR.

**Comment by bowbahdoe** [comment]
Ah, no problem man.

**Pull request closed without merging**
